name: memo_notes
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  #Visual elements
  animate_do: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  bottom_picker: ^1.0.6
  cool_alert: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  lottie: ^1.1.0
  animated_flip_counter: ^0.1.2

  #State mangment
  bloc: ^7.0.0
  bloc_test: ^8.1.0
  equatable: ^2.0.3
  flutter_bloc: ^7.0.0
  hydrated_bloc: ^7.0.0

  #Cache
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2

  #Localization
  easy_localization: ^3.0.0


  #Notification
  flutter_local_notifications: ^9.0.2
  rxdart: ^0.27.2
  flutter_native_timezone: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_screenutil: ^5.0.1
  lint: ^1.6.0
  flutter_launcher_icons: ^0.9.2
  json_serializable: any
  json_annotation: any
  build_runner: any

flutter_icons:
  image_path: "assets/images/png/launcher_icon.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/images/
    - assets/images/svg/
    - assets/images/lottie/

  fonts:
    - family: MyIcon
      fonts:
        - asset: assets/fonts/MyFlutterIcons.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
